name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
       persist-credentials: false

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libpcap-dev

    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: brew install libpcap

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
      
